apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyally-products-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products-api
        image: pallavi57/productservice
        ports:
        - containerPort: 6000        
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  ports:
  - port: 6000
    name: http
    targetPort: 6000
  selector:
    app: products

