apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyally-users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-api
        image: pallavi57/userservice
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000 
  selector:
    app: users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyally-rabbitmq-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-api
        image: rabbitmq
        ports:
        - containerPort: 5672 
        - containerPort: 15672 
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
spec:
  ports:
  - port: 5672
    name: http
    targetPort: 5672
  - port: 15672
    name: http2
    targetPort: 15672 
  
  selector:
    app: rabbitmq    


