version: "3.8"
services:
  rabbitmq3:
    hostname: "rabbitmq"
    image: rabbitmq:3.8-management-alpine 
    environment:
      - RABBITMQ_DEFAULT_USER=pallavi57
      - RABBITMQ_DEFAULT_PASS=pallavi57
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

    volumes:
      - ./rabbitmq/etc:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log

  userservice:
    container_name: "userservice"
    image: pallavi57/userservice
    build:
      context: .
      dockerfile: ./Dockerfile.Users
    ports:
      - 5000:5000
