apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loyally-ingress
  namespace: kong
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
       - path: /api/*
         pathType: Prefix
         backend:
          service:
            name: users-service
            port:
              number: 5000


